<a href="https://colab.research.google.com/github/Aleksandra191/PUM_projekt_NA_EM_AK/blob/main/Projekt_PUM_Ola.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Celem jest predykcja ceny nieruchomości.

Zbiór danych zawiera 4802 instancje i kolumny określające:

- BROKERTITLE: Title of the broker
- TYPE: Type of the house
- PRICE: Price of the house
- BEDS: Number of bedrooms
- BATH: Number of bathrooms
-PROPERTYSQFT: Square footage of the property
-ADDRESS: Full address of the house
-STATE: State of the house
-MAIN_ADDRESS: Main address information
-ADMINISTRATIVE_AREA_LEVEL_2: Administrative area level 2 information
-LOCALITY: Locality information
-SUBLOCALITY: Sublocality information
-STREET_NAME: Street name
-LONG_NAME: Long name
-FORMATTED_ADDRESS: Formatted address
-LATITUDE: Latitude coordinate of the house
-LONGITUDE: Longitude coordinate of the house

In [704]:
import pandas as pd

In [705]:
url = 'https://raw.githubusercontent.com/Aleksandra191/PUM_projekt_NA_EM_AK/main/NY-House-Dataset.csv'
data = pd.read_csv(url, sep= ';')
data.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856

In [706]:
data.shape

(4801, 17)

In [707]:
data.drop_duplicates(inplace = True)
data.shape

(4587, 17)

In [708]:
data.dtypes

BROKERTITLE                     object
TYPE                            object
PRICE                            int64
BEDS                             int64
BATH                           float64
PROPERTYSQFT                   float64
ADDRESS                         object
STATE                           object
MAIN_ADDRESS                    object
ADMINISTRATIVE_AREA_LEVEL_2     object
LOCALITY                        object
SUBLOCALITY                     object
STREET_NAME                     object
LONG_NAME                       object
FORMATTED_ADDRESS               object
LATITUDE                       float64
LONGITUDE                      float64
dtype: object

In [709]:
data.groupby(data["BATH"])["BATH"].count().sort_values(ascending = False)
data["BATH"] = data["BATH"].astype(int)

In [710]:
data.isna().sum()

BROKERTITLE                    0
TYPE                           0
PRICE                          0
BEDS                           0
BATH                           0
PROPERTYSQFT                   0
ADDRESS                        0
STATE                          0
MAIN_ADDRESS                   0
ADMINISTRATIVE_AREA_LEVEL_2    0
LOCALITY                       0
SUBLOCALITY                    0
STREET_NAME                    0
LONG_NAME                      0
FORMATTED_ADDRESS              0
LATITUDE                       0
LONGITUDE                      0
dtype: int64

In [711]:
#Drop outlier by IQR calculation
def outliers(data, nameOfColumn):
  Q1 = data[nameOfColumn].quantile(0.25)
  Q3 = data[nameOfColumn].quantile(0.75)
  IQR = Q3 - Q1
  data.drop(data.loc[data[nameOfColumn] > (Q3 + 1.5 * IQR)].index, inplace= True)
  data.drop(data.loc[data[nameOfColumn] < (Q1- 1.5 * IQR)].index, inplace = True)

In [712]:
data.describe()

,PRICE,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE
count,4.587000e+03,4587.000000,4587.000000,4587.000000,4587.000000,4587.000000
mean,2.381172e+06,3.365816,2.354262,2177.712426,40.713932,-73.941584
std,3.206831e+07,2.628808,1.970637,2283.095559,0.087738,0.101276
min,2.494000e+03,1.000000,0.000000,230.000000,40.499546,-74.253033
25%,4.990000e+05,2.000000,1.000000,1200.000000,40.638588,-73.987420
50%,8.250000e+05,3.000000,2.000000,2184.207862,40.726667,-73.949116
75%,1.498500e+06,4.000000,3.000000,2184.207862,40.771913,-73.869455
max,2.147484e+09,50.000000,50.000000,65535.000000,40.912729,-73.702450

In [713]:
data.drop(data.loc[(data["PRICE"] > 100000000) | (data["PRICE"]<10000)].index, inplace= True)

In [714]:
data.groupby(data["BEDS"])["BEDS"].count().sort_values(ascending = False)
#outliers(data, "BEDS") - możemy użyć tej metody wtedy usuwa wszystkie rekordy z więcej niż 7 sypialniami (co ma sens)
#data.drop(data.loc[data["BEDS"] > 20].index, inplace= True) - albo możemy ustalić od ilu usuwamy

BEDS
3     1395
2      949
1      779
4      544
5      339
6      260
7       98
8       81
9       38
12      22
10      21
11      20
14       6
13       5
15       5
16       4
20       3
24       3
32       2
18       1
19       1
30       1
35       1
36       1
40       1
42       1
50       1
Name: BEDS, dtype: int64

In [715]:
data.groupby(data["BATH"])["BATH"].count().sort_values(ascending = False)
outliers(data, "BATH")
data.groupby(data["BATH"])["BATH"].count().sort_values(ascending = False)

BATH
2    1880
1    1454
4     464
3     447
6     133
5      95
0       2
Name: BATH, dtype: int64

In [716]:
data.shape
outliers(data, "PROPERTYSQFT")
data.shape

(4180, 17)

In [717]:
len(data["BROKERTITLE"].unique())
data["BROKERTITLE"].unique()

array(['Brokered by Douglas Elliman  -111 Fifth Ave',
       'Brokered by Sowae Corp', 'Brokered by COMPASS', ...,
       'Brokered by Fine Choice Realty Inc',
       'Brokered by Silverside Realty LLC',
       'Brokered by New York Way Real Estate Corp'], dtype=object)

In [718]:
data["TYPE"].unique()
data["TYPE"] = data["TYPE"].str.replace(" for sale", "")
data["TYPE"] = data["TYPE"].str.replace("Condop", "Condo")
lackOfData = ["For sale", "Pending", "Coming Soon"]
for i in lackOfData:
  data["TYPE"] = data["TYPE"].str.replace(i, "Lack of data")
data.groupby(data["TYPE"])["TYPE"].count().sort_values(ascending = False)

TYPE
Co-op                1373
House                 895
Condo                 801
Multi-family home     574
Lack of data          232
Townhouse             164
Contingent             82
Land                   46
Foreclosure            12
Mobile house            1
Name: TYPE, dtype: int64

In [719]:
(data["ADDRESS"] + data["STATE"] == data["MAIN_ADDRESS"]).unique()
data.drop("MAIN_ADDRESS", axis=1, inplace=True)

In [720]:
dictLocality = {"New York County": "Manhattan",  "Kings County":"Brooklyn","Bronx County":"The Bronx", "Richmond County": "Staten Island", "Queens County":"Queens"}
listOfBoroughs = list(dictLocality.values())

In [721]:
for c in list(data.columns):
  for i in list(dictLocality.keys()):
    data[c] = data[c].astype(str).str.replace(i, dictLocality[i])

In [722]:
data["LOCALITY"].unique()
data.loc[data["LOCALITY"].isin(['Manhattan', 'The Bronx', 'Brooklyn', 'Queens', 'Staten Island']), "BOROUGH"] = data['LOCALITY']
data["BOROUGH"].unique()
data.loc[data["LOCALITY"] == "Flatbush", "NEIGHBOURHOOD"] = data['LOCALITY']

In [723]:
data["SUBLOCALITY"].unique()
data.loc[(data["SUBLOCALITY"].isin(listOfBoroughs)) &(data["BOROUGH"].isna()) , "BOROUGH"] = data["SUBLOCALITY"]
data.loc[data["SUBLOCALITY"] == "Snyder Avenue" , "STREET"] = data["SUBLOCALITY"]
data.loc[(data["SUBLOCALITY"].isin(list(filter(lambda x: x not in listOfBoroughs, list(data["SUBLOCALITY"]))))) & (~(data["SUBLOCALITY"].isin(["New York", "Snyder Avenue"]))) , "NEIGHBOURHOOD"] = data["SUBLOCALITY"]
data

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE,BOROUGH,NEIGHBOURHOOD,STREET
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo,315000,2,2,1400.0,2 E 55th St Unit 803,"New York, NY 10022",Manhattan,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.9744834,Manhattan,NaN,NaN
2,Brokered by Sowae Corp,House,260000,4,2,2015.0,620 Sinclair Ave,"Staten Island, NY 10312",United States,New York,Staten Island,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.5418051,-74.1961086,Staten Island,NaN,NaN
3,Brokered by COMPASS,Condo,69000,3,1,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022",United States,New York,Manhattan,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.7613979,-73.9746128,Manhattan,NaN,NaN
6,Brokered by Douglas Elliman - 575 Madison Ave,Condo,899500,2,2,2184.207862,157 W 126th St Unit 1B,"New York, NY 10027",New York,Manhattan,New York,Manhattan,157,"157 W 126th St #1b, New York, NY 10027, USA",40.809448,-73.946777,Manhattan,NaN,NaN
8,Brokered by Pantiga Group Inc.,Co-op,265000,1,1,750.0,875 Morrison Ave Apt 3M,"Bronx, NY 10473",The Bronx,The Bronx,East Bronx,Morrison Avenue,Parking lot,"Parking lot, 875 Morrison Ave #3m, Bronx, NY 1...",40.8215857,-73.8740892,The Bronx,East Bronx,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op,599000,1,1,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075",New York,Manhattan,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.77435,-73.955879,Manhattan,NaN,NaN
4797,Brokered by Mjr Real Estate Llc,Co-op,245000,1,1,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374",United States,New York,Queens,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.7325379,-73.8601516,Queens,NaN,NaN
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op,1275000,1,1,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011",United States,New York,Manhattan,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.7458817,-74.0033976,Manhattan,NaN,NaN
4799,Brokered by E Realty International Corp,Condo,598125,2,1,655.0,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373",New York,Queens,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.7427705,-73.8727516,Queens,NaN,NaN
4800,Brokered by Nyc Realty Brokers Llc,Co-op,349000,1,1,750.0,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224",New York,Brooklyn,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.9709488,Brooklyn,NaN,NaN

In [724]:
data["ADMINISTRATIVE_AREA_LEVEL_2"].unique()

array(['Manhattan', 'United States', 'New York', 'The Bronx', '10301',
       '10309', '10303', '11234', '11414', '10310', '10003', '11417',
       'Brooklyn', '11214', '10463', 'Queens', '10017', '10306', '10471',
       '11229', '10312', '11412', '10465', '10466', '11237', '11218',
       '10002'], dtype=object)

In [725]:
data["ADMINISTRATIVE_AREA_LEVEL_2"].unique()
data.loc[(data["ADMINISTRATIVE_AREA_LEVEL_2"].isin(listOfBoroughs)) &(data["BOROUGH"].isna()) , "BOROUGH"] = data["ADMINISTRATIVE_AREA_LEVEL_2"]
data.loc[(data["ADMINISTRATIVE_AREA_LEVEL_2"].isin(list(filter(lambda x: x not in listOfBoroughs, list(data["ADMINISTRATIVE_AREA_LEVEL_2"]))))) & (data["ADMINISTRATIVE_AREA_LEVEL_2"] != "New York") & (data["ADMINISTRATIVE_AREA_LEVEL_2"] != "United States") , "POSTCODE"] = data["ADMINISTRATIVE_AREA_LEVEL_2"]

In [726]:
data["STREET_NAME"].unique()

array(['East 55th Street', 'Staten Island', 'New York', 'Manhattan',
       'Morrison Avenue', 'Midwood', 'Concourse Village', 'Flushing',
       'Elmhurst', 'Annadale', 'Queens', 'Fort Hamilton',
       'North Riverdale', 'Rego Park', 'Forest Hills', 'The Bronx',
       'Dongan Hills', 'Jackson Heights', 'Clifton', 'Brooklyn',
       'Dyker Heights', 'Williamsburg', 'Concourse', 'Mid Island',
       'Centre Street', 'Cobble Hill', 'Park Slope', 'Brighton Beach',
       'Flatbush', 'Prospect Heights', 'Woodhaven', 'Bedford-Stuyvesant',
       'Jamaica', 'Spuyten Duyvil', 'Bay Ridge', 'Shore Acres', 'Bayside',
       'Glen Oaks', 'Fresh Meadows', 'Highbridge', 'Sheepshead Bay',
       'Rector Place', 'Kew Gardens', 'Bushwick', 'Hudson Hill',
       'Rosedale', 'East Bronx', 'Parkchester', 'Borough Park',
       'Brooklyn Heights', 'Little Haiti', 'Canarsie', 'Kensington',
       'East 110th Street', 'East New York', 'Pelham Bay', 'Howard Beach',
       'Downtown Brooklyn', 'City Island', 'Fieldston',
       'Westchester Square', 'Rockaway Park', 'Riverdale', 'Bulls Head',
       'Gerritsen Beach', 'Crown Heights', 'New Dorp', 'West Bronx',
       'Ocean Hill', 'Gravesend', 'Castleton Corners', 'Seagate',
       'Gowanus', 'Windsor Terrace', 'Bath Beach', 'Norwood',
       'Whitestone', 'Surf Avenue', 'Great Kills', 'Homecrest',
       'Long Island City', 'Woodside', 'Maspeth', 'Sunset Park',
       'Douglaston', 'Queens Village', 'Astoria', 'Dumbo',
       'New Springville', 'Corona', 'Madison', 'Bensonhurst',
       'Fordham Manor', 'Greenpoint', 'Coney Island', 'Mill Basin',
       'Carroll Gardens', 'Old Fulton Street', 'Ozone Park',
       'East 74th Street', 'Floral Park', '35th Avenue', 'Far Rockaway',
       'Beechhurst', 'Henry Hudson Parkway', 'Rosebank', 'Kingsbridge',
       'Bergen Beach', 'Ridgewood', 'Oakwood', 'Clinton Hill',
       'Richmond Hill', 'Auburndale', 'Southside', 'Little Caribbean',
       'Mariners Harbor', 'Fort Greene', 'Boerum Hill', 'Foxhurst',
       'Red Hook', 'Columbia Street Waterfront District', 'Sunnyside',
       'Flatlands', 'Mapleton', '98th Place', 'East 22nd Street',
       'Manhattan Beach', 'East Elmhurst', 'East Flatbush',
       'Oxford Avenue', 'Bay Terrace', 'Arverne', 'Midland Beach',
       'Vinegar Hill', 'Little Neck', 'West Brighton', 'East 96th Street',
       'Clason Point', '5th Avenue', 'Shore Road', 'West 56th Street',
       'Middle Village', 'West 111th Street', 'Prospect Lefferts Gardens',
       'Woodstock', 'Melrose', 'East 10th Street', '139th Street',
       'Park Avenue', 'West 65th Street', 'John Street',
       'East End Avenue', 'Brownsville', '3G', 'West 13th Street',
       'College Point', 'Central Park West', 'East 88th Street',
       'Allerton', 'Morrisania', 'West 64th Street', '61st Street',
       'Cypress Hills', '2501', '67th Drive', 'Todt Hill',
       'Saunders Street', 'Mount Eden'], dtype=object)

In [727]:
streets = []
keyWords = ["Street", "Parkway", "Avenue", "Drive"]
for street_name in data["STREET_NAME"]:
    for keyword in keyWords:
        if keyword in street_name:
            streets.append(street_name)
            break

streets

['East 55th Street',
 'Morrison Avenue',
 'Centre Street',
 'East 110th Street',
 'Surf Avenue',
 'Old Fulton Street',
 'East 74th Street',
 '35th Avenue',
 'Henry Hudson Parkway',
 'Surf Avenue',
 'Columbia Street Waterfront District',
 'East 22nd Street',
 'Oxford Avenue',
 'East 96th Street',
 '5th Avenue',
 'West 56th Street',
 'West 111th Street',
 'East 10th Street',
 '139th Street',
 'Park Avenue',
 'West 65th Street',
 'John Street',
 'East End Avenue',
 '5th Avenue',
 'West 13th Street',
 'Oxford Avenue',
 'East 88th Street',
 'West 64th Street',
 '61st Street',
 '67th Drive',
 'Saunders Street',
 'East 55th Street',
 'West 56th Street',
 'Surf Avenue']

In [728]:
data.loc[(data["STREET_NAME"].isin(listOfBoroughs))& (data["BOROUGH"].isna()), "BOROUGH"] = data["STREET_NAME"]
data.loc[(data["STREET_NAME"].isin(list(filter(lambda x: (x not in streets) & (x != "New York") & (x not in listOfBoroughs), list(data["STREET_NAME"]))))) & (data["NEIGHBOURHOOD"].isna()), "NEIGHBOURHOOD"] = data["STREET_NAME"]
data.loc[(data["STREET_NAME"].isin(streets)) & (data["STREET"].isna()), "STREET"] = data["STREET_NAME"]

In [729]:
data["STATE"].unique()
data.loc[data["POSTCODE"].isna(), "POSTCODE"] = data["STATE"].str.slice(-5)
data.loc[(data["BOROUGH"].isna()) &(data["STATE"].str.split(", ").str.get(0).isin(listOfBoroughs)) , "BOROUGH"] = data["STATE"].str.split(", ").str.get(0)
data.loc[(data["NEIGHBOURHOOD"].isna()) & (~(data["STATE"].str.split(", ").str.get(0).isin(listOfBoroughs))) &(~(data["STATE"].str.split(", ").str.get(0).isin(["New York", "Ny", "Nyc" ]))) , "NEIGHBOURHOOD"] = data["STATE"].str.split(", ").str.get(0)

In [730]:
data.loc[data["POSTCODE"].isna(), "POSTCODE"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-2).str.slice(-5)
data.loc[(data["BOROUGH"].isna()) & (data["FORMATTED_ADDRESS"].str.split(", ").str.get(-3).isin(listOfBoroughs)), "BOROUGH"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-3)
data.loc[(data["NEIGHBOURHOOD"].isna()) & (~(data["FORMATTED_ADDRESS"].str.split(", ").str.get(-3).isin(listOfBoroughs))) & (~(data["FORMATTED_ADDRESS"].str.split(", ").str.get(-3).isin(["New York"]))), "NEIGHBOURHOOD"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-3)

In [731]:
data.loc[data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4).str.split().str.get(0).str.replace("-","").str.contains('\d'), "HOUSE_NUMBER"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4).str.split().str.get(0)
data.loc[(data["STREET"].isna()) & (data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4).str.split().str.get(0).str.replace("-","").str.contains('\d')), "STREET"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4).str.split().str.slice(start=1).str.join(" ")
data.loc[(data["STREET"].isna()) & (~(data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4).str.split().str.get(0).str.replace("-","").str.contains('\d'))), "STREET"] = data["FORMATTED_ADDRESS"].str.split(", ").str.get(-4)

In [732]:
data.loc[(data["LONG_NAME"].str.replace("-", "").str.isdigit()), "HOUSE_NUMBER"] = data["LONG_NAME"]
data.loc[(~(data["LONG_NAME"].str.replace("-", "").str.isdigit())) & (data["STREET"].isna()) & (data["LONG_NAME"] != "Parking lot"), "STREET"] = data["LONG_NAME"]

In [733]:
data.loc[(data["ADDRESS"].str.split(" ").str.get(0).str.replace("-", "").str.isdigit()) & (data["HOUSE_NUMBER"].isna()), "HOUSE_NUMBER"] = data["ADDRESS"].str.split(" ").str.get(0).str.split().str.get(0)

In [734]:
data.loc[data["ADDRESS"] == "98A-98G Discala Ln", "HOUSE_NUMBER"] = "98A-98G"

In [735]:
data.loc[data["STREET"].isna(), "STREET"] = ""

In [736]:
data.loc[data["STREET"].str.contains(r'\bSt\b'), "STREET"] = data["STREET"].str.replace("St", "Street")
data.loc[data["STREET"].str.contains(r'\bAve\b'), "STREET"] = data["STREET"].str.replace("Ave", "Avenue")
data.loc[data["STREET"].str.contains(r'\bE\b'), "STREET"] = data["STREET"].str.replace("E", "East")
data.loc[data["STREET"].str.contains(r'\bW\b'), "STREET"] = data["STREET"].str.replace("W", "West")
data.loc[data["STREET"].str.contains(r'\bS\b'), "STREET"] = data["STREET"].str.replace("S", "South")
data.loc[data["STREET"].str.contains(r'\bN\b'), "STREET"] = data["STREET"].str.replace("N", "North")
data.loc[data["STREET"].str.contains(r'\bDr\b'), "STREET"] = data["STREET"].str.replace("Dr", "Drive")
data.loc[data["STREET"].str.contains(r'\bCt\b'), "STREET"] = data["STREET"].str.replace("Ct", "Court")
data.loc[data["STREET"].str.contains(r'\bCt\b'), "STREET"] = data["STREET"].str.replace("Rd", "Road")
data.loc[data["STREET"].str.contains(r'\bBlvd\b'), "STREET"] = data["STREET"].str.replace("Blvd", "Boulevard")

data.loc[data["STREET"].str.contains(r' #.*'), "STREET"] = data["STREET"].str.replace(r' #.*', "")
data["STREET"]= data["STREET"].str.replace(".", "")
data["STREET"].unique()

<ipython-input-736-6c6ea4c6daac>:12: FutureWarning: The default value of regex will change from True to False in a future version.
  data.loc[data["STREET"].str.contains(r' #.*'), "STREET"] = data["STREET"].str.replace(r' #.*', "")
<ipython-input-736-6c6ea4c6daac>:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["STREET"]= data["STREET"].str.replace(".", "")

array(['East 55th Street', 'Sinclair Avenue', 'West 126th Street', ...,
       '85th Avenue', 'Lafayette Street RM 502',
       'Adam Clayton Powell Jr Boulevard Apartment 614'], dtype=object)

In [737]:
data.to_excel("output.xlsx")

In [738]:
data.drop("STATE", axis=1, inplace=True)
data.drop("ADMINISTRATIVE_AREA_LEVEL_2", axis=1, inplace=True)
data.drop("LOCALITY", axis=1, inplace=True)
data.drop("SUBLOCALITY", axis=1, inplace=True)
data.drop("STREET_NAME", axis=1, inplace=True)
data.drop("LONG_NAME", axis=1, inplace=True)
data.drop("FORMATTED_ADDRESS", axis=1, inplace=True)

In [744]:
data.isna().sum()
data.loc[data["NEIGHBOURHOOD"].isna(), "NEIGHBOURHOOD"] = ""
data.loc[data["HOUSE_NUMBER"].isna(), "HOUSE_NUMBER"] = ""

BROKERTITLE      0
TYPE             0
PRICE            0
BEDS             0
BATH             0
PROPERTYSQFT     0
ADDRESS          0
LATITUDE         0
LONGITUDE        0
BOROUGH          0
NEIGHBOURHOOD    0
STREET           0
POSTCODE         0
HOUSE_NUMBER     0
dtype: int64